/**
 * Canonical Workflow State Machine & Transition Rules (Backend)
 */

const WORKFLOW_STATES = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  AI_PROCESSING: 'AI_PROCESSING',
  AI_FAILED: 'AI_FAILED',
  PENDING_ADMIN_REVIEW: 'PENDING_ADMIN_REVIEW',
  ROUTED: 'ROUTED',
  DEPARTMENT_ACCEPTED: 'DEPARTMENT_ACCEPTED',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED_BY_ENGINEER: 'ACCEPTED_BY_ENGINEER',
  EN_ROUTE: 'EN_ROUTE',
  ON_SITE: 'ON_SITE',
  IN_PROGRESS: 'IN_PROGRESS',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  DEPARTMENT_REVIEW: 'DEPARTMENT_REVIEW',
  CITIZEN_VERIFICATION: 'CITIZEN_VERIFICATION',
  REOPENED: 'REOPENED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED'
});

const ROLES = Object.freeze({
  CITIZEN: 'citizen',
  ENGINEER: 'engineer',
  DEPARTMENT: 'department',
  ADMIN: 'admin'
});

const WORKFLOW_TRANSITIONS = Object.freeze({
  [WORKFLOW_STATES.SUBMITTED]: [
    { to: WORKFLOW_STATES.AI_PROCESSING, roles: [ROLES.ADMIN, 'system'] },
    { to: WORKFLOW_STATES.PENDING_ADMIN_REVIEW, roles: [ROLES.ADMIN, 'system'] },
    { to: WORKFLOW_STATES.ROUTED, roles: [ROLES.ADMIN, 'system'] }
  ],
  [WORKFLOW_STATES.AI_PROCESSING]: [
    { to: WORKFLOW_STATES.ROUTED, roles: [ROLES.ADMIN, 'system'] },
    { to: WORKFLOW_STATES.PENDING_ADMIN_REVIEW, roles: [ROLES.ADMIN, 'system'] },
    { to: WORKFLOW_STATES.AI_FAILED, roles: [ROLES.ADMIN, 'system'] }
  ],
  [WORKFLOW_STATES.AI_FAILED]: [
    { to: WORKFLOW_STATES.AI_PROCESSING, roles: [ROLES.ADMIN] },
    { to: WORKFLOW_STATES.PENDING_ADMIN_REVIEW, roles: [ROLES.ADMIN] },
    { to: WORKFLOW_STATES.ROUTED, roles: [ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.PENDING_ADMIN_REVIEW]: [
    { to: WORKFLOW_STATES.ROUTED, roles: [ROLES.ADMIN] },
    { to: WORKFLOW_STATES.REJECTED, roles: [ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.ROUTED]: [
    { to: WORKFLOW_STATES.DEPARTMENT_ACCEPTED, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] },
    { to: WORKFLOW_STATES.ASSIGNED, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] },
    { to: WORKFLOW_STATES.PENDING_ADMIN_REVIEW, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] },
    { to: WORKFLOW_STATES.REJECTED, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.DEPARTMENT_ACCEPTED]: [
    { to: WORKFLOW_STATES.ASSIGNED, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] },
    { to: WORKFLOW_STATES.ROUTED, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.ASSIGNED]: [
    { to: WORKFLOW_STATES.ACCEPTED_BY_ENGINEER, roles: [ROLES.ENGINEER, ROLES.ADMIN] },
    { to: WORKFLOW_STATES.DEPARTMENT_ACCEPTED, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.ACCEPTED_BY_ENGINEER]: [
    { to: WORKFLOW_STATES.EN_ROUTE, roles: [ROLES.ENGINEER] }
  ],
  [WORKFLOW_STATES.EN_ROUTE]: [
    { to: WORKFLOW_STATES.ON_SITE, roles: [ROLES.ENGINEER] }
  ],
  [WORKFLOW_STATES.ON_SITE]: [
    { to: WORKFLOW_STATES.IN_PROGRESS, roles: [ROLES.ENGINEER] }
  ],
  [WORKFLOW_STATES.IN_PROGRESS]: [
    { to: WORKFLOW_STATES.VERIFICATION_PENDING, roles: [ROLES.ENGINEER] }
  ],
  [WORKFLOW_STATES.VERIFICATION_PENDING]: [
    { to: WORKFLOW_STATES.DEPARTMENT_REVIEW, roles: [ROLES.DEPARTMENT, ROLES.ADMIN, 'system'] },
    { to: WORKFLOW_STATES.CITIZEN_VERIFICATION, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] },
    { to: WORKFLOW_STATES.IN_PROGRESS, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.DEPARTMENT_REVIEW]: [
    { to: WORKFLOW_STATES.CITIZEN_VERIFICATION, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] },
    { to: WORKFLOW_STATES.IN_PROGRESS, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.CITIZEN_VERIFICATION]: [
    { to: WORKFLOW_STATES.CLOSED, roles: [ROLES.CITIZEN, ROLES.ADMIN] },
    { to: WORKFLOW_STATES.REOPENED, roles: [ROLES.CITIZEN, ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.REOPENED]: [
    { to: WORKFLOW_STATES.DEPARTMENT_REVIEW, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] },
    { to: WORKFLOW_STATES.IN_PROGRESS, roles: [ROLES.DEPARTMENT, ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.REJECTED]: [
    { to: WORKFLOW_STATES.PENDING_ADMIN_REVIEW, roles: [ROLES.ADMIN] }
  ],
  [WORKFLOW_STATES.CLOSED]: []
});

function canTransition(currentStatus, targetStatus, userRole) {
  if (!currentStatus || !targetStatus) return false;
  const curr = String(currentStatus).toUpperCase();
  const tgt = String(targetStatus).toUpperCase();
  if (curr === tgt) return true;

  if (userRole === ROLES.ADMIN) return true;

  const allowed = WORKFLOW_TRANSITIONS[curr];
  if (!allowed) return false;

  const match = allowed.find(t => t.to === tgt);
  if (!match) return false;

  const roleNormalized = (userRole || '').toLowerCase();
  return match.roles.includes(roleNormalized) || match.roles.includes('system');
}

module.exports = {
  WORKFLOW_STATES,
  ROLES,
  WORKFLOW_TRANSITIONS,
  canTransition
};
